name = "intervinn/indium"
version = "0.1.0"
description = "Express-like Lune backend"
authors = ["intervinn"]
repository = "https://github.com/intervinn/indium"
license = "MIT"

[target]
environment = "lune"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
